# -*- coding: utf-8 -*-
"""Project2-Question3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P8cbyTvxv0H2z3BVmZutZ7QI09ux-dkr

# **Project2**
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit

# Commented out IPython magic to ensure Python compatibility.
# %pip install langchain-ollama

import streamlit as st

st.title("Input to AI")
Question = st.text_input("Enter your question:")

Attachment = st.file_uploader("Upload attachment:")

st.title("AI Response:")

def simple_ai(Question, context):
    if context:
      st.write("The AI is using the uploaded document as context.")
    else:
      st.write( "I'm happy to play along.\n\n"
               "Since the context is empty, I'll answer directly.\n\nI am an AI designed to simulate human-like conversations and provide information on a wide range of topics. I don't have personal experiences, emotions, or physical presence, but I'm here to help answer your questions and engage in discussions to the best of my abilities."
        )

if Question:
    context = ""

    if Attachment is not None:
        context = Attachment.read().decode("utf-8")

    response = simple_ai(Question, context)
    st.write(response)

#Question 3 Deployment Bonus

#